Shoplify/Shoplify.Web/Areas/Administration/ViewModels/Advertisement/AdvertisementPromoteViewModel.cs
namespace Shoplify.Web.Areas.Administration.ViewModels.Advertisement
{
    public class AdvertisementPromoteViewModel
    {
        public string Id { get; set; }
    }
}

Shoplify/Shoplify.Web/ViewModels/Advertisement/PromoteViewModel.cs
namespace Shoplify.Web.ViewModels.Advertisement
{
    public class PromoteViewModel
    {
        public string Id { get; set; }
    }
}

Shoplify/Shoplify.Web/Areas/Administration/Controllers/AdvertisementController.cs
namespace Shoplify.Web.Areas.Administration.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Common;
    using Shoplify.Domain;
    using Shoplify.Services.Interfaces;
    using Shoplify.Web.Areas.Administration.BindingModels.Advertisement;
    using Shoplify.Web.Areas.Administration.ViewModels.Advertisement;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdvertisementController : Controller
    {
        private readonly IAdvertisementService advertisementService;
        private readonly INotificationService notificationService;
        private readonly IUserAdWishlistService userAdWishlistService;
        private readonly UserManager<User> userManager;

        public AdvertisementController(IAdvertisementService advertisementService, INotificationService notificationService, IUserAdWishlistService userAdWishlistService, UserManager<User> userManager)
        {
            this.userManager = userManager;
            this.notificationService = notificationService;
            this.userAdWishlistService = userAdWishlistService;
            this.advertisementService = advertisementService;
        }

        public async Task<IActionResult> All(int page = 1)
        {
            if (page <= 0)
            {
                return Redirect("/Panel/Index");
            }

            var adsCount = await advertisementService.GetAllAdsCountAsync();
            var lastPage = adsCount / GlobalConstants.AdsPerAdminPanelPageCount + 1;

            if (adsCount % GlobalConstants.AdsPerAdminPanelPageCount == 0 && adsCount > 0)
            {
                lastPage -= 1;
            }

            if (page > lastPage)
            {
                return Redirect("/Panel/Index");
            }

            var ads = await advertisementService.GetAllAdsAsync(page, GlobalConstants.AdsPerAdminPanelPageCount);

            var viewModel = new AdvertisementListingPageViewModel
            {
                TotalAdsCount = adsCount,
                CurrentPage = page,
                LastPage = lastPage,
                Ads = new List<AdvertisementViewModel>()
            };

            foreach (var ad in ads)
            {
                var adOwner = await userManager.FindByIdAsync(ad.UserId);

                viewModel.Ads.Add(new AdvertisementViewModel
                {
                    Id = ad.Id,
                    ArchivedOn = ad.ArchivedOn.ToString(GlobalConstants.DateTimeFormat),
                    BannedOn = ad.BannedOn.ToString(GlobalConstants.DateTimeFormat),
                    CreatedOn = ad.CreatedOn.ToString(GlobalConstants.DateTimeFormat),
                    IsArchived = ad.IsArchived,
                    IsPromoted = ad.IsPromoted,
                    IsBanned = ad.IsBanned,
                    Name = ad.Name,
                    OwnerId = ad.UserId,
                    OwnerName = adOwner.UserName,
                    PromotedUntil = ad.PromotedUntil.ToString(GlobalConstants.DateTimeFormat),
                    Views = ad.Views
                });
            }

            return View(viewModel);
        }

        public async Task<IActionResult> CreatedThisWeek()
        {
            var adsCountByDays = await advertisementService.GetNewAdsCountByDaysFromThisWeekAsync();

            return Json(adsCountByDays);
        }

        public async Task<IActionResult> CountByCategories()
        {
            var adsCountByCategories = await advertisementService.GetAdsCountByCategoriesAsync();

            return Json(adsCountByCategories);
        }

        public IActionResult Promote(string adId)
        {
            if (!advertisementService.Contains(adId))
            {
                return RedirectToAction("All");
            }

            return View(new AdvertisementPromoteViewModel{ Id = adId });
        }

        [HttpPost]
        public async Task<IActionResult> Promote(PromoteBindingModel input)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("All");
            }

            var days = int.Parse(input.Days);
            var ad = await advertisementService.GetByIdAsync(input.Id);

            await advertisementService.PromoteByIdAsync(ad.Id, days);

            var notificationText = $"Your ad has been promoted for {days} days by admin - '{ad.Name}'";
            var actionLink = $"/Advertisement/Details?id={ad.Id}";

            var notification = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUserAsync(notification.Id, ad.UserId);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> UnPromote(string adId)
        {
            var ad = await advertisementService.GetByIdAsync(adId);

            if (ad == null)
            {
                return RedirectToAction("All");
            }

            await advertisementService.UnpromoteByIdAsync(ad.Id);

            var notificationText = $"Your ad has been unpromoted by admin - '{ad.Name}'";
            var actionLink = $"/Advertisement/Details?id={ad.Id}";

            var notification = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUserAsync(notification.Id, ad.UserId);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Ban(string adId)
        {
            var ad = await advertisementService.GetByIdAsync(adId);

            if (ad == null)
            {
                return RedirectToAction("All");
            }

            await advertisementService.BanByIdAsync(ad.Id);

            var notificationText = $"Your ad has been banned by admin - '{ad.Name}'";
            var actionLink = $"/User/Profile?id={ad.Id}";

            var notificationToAdOwner = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUserAsync(notificationToAdOwner.Id, ad.UserId);

            notificationText = $"Ad in your wishlist has been banned by admin - '{ad.Name}'";
            actionLink = $"/User/Wishlist";

            var usersIds = await userAdWishlistService.GetAllUserIdsThatHaveAdInWishlistAsync(ad.Id);

            var notificationToAllUsersThatHaveAdInWishlist = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUsersAsync(notificationToAllUsersThatHaveAdInWishlist.Id, usersIds.ToList());

            return RedirectToAction("All");
        }

        public async Task<IActionResult> UnBan(string adId)
        {
            var ad = await advertisementService.GetByIdAsync(adId);

            if (ad == null)
            {
                return RedirectToAction("All");
            }

            await advertisementService.UnbanByIdAsync(ad.Id);

            var notificationText = $"Your ad has been unbanned by admin - '{ad.Name}'";
            var actionLink = $"/User/Profile?id={ad.Id}";

            var notificationToAdOwner = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUserAsync(notificationToAdOwner.Id, ad.UserId);

            notificationText = $"Ad in your wishlist has been unbanned by admin - '{ad.Name}'";
            actionLink = $"/User/Wishlist";

            var usersIds = await userAdWishlistService.GetAllUserIdsThatHaveAdInWishlistAsync(ad.Id);

            var notificationToAllUsersThatHaveAdInWishlist = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUsersAsync(notificationToAllUsersThatHaveAdInWishlist.Id, usersIds.ToList());

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Archive(string adId)
        {
            var ad = await advertisementService.GetByIdAsync(adId);

            if (ad == null)
            {
                return RedirectToAction("All");
            }

            await advertisementService.ArchiveByIdAsync(ad.Id);

            var notificationText = $"Your ad has been archived by admin - '{ad.Name}'";
            var actionLink = $"/User/Profile?id={ad.Id}";

            var notificationToAdOwner = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUserAsync(notificationToAdOwner.Id, ad.UserId);

            notificationText = $"Ad in your wishlist has been archived by admin - '{ad.Name}'";
            actionLink = $"/User/Wishlist";

            var usersIds = await userAdWishlistService.GetAllUserIdsThatHaveAdInWishlistAsync(ad.Id);

            var notificationToAllUsersThatHaveAdInWishlist = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUsersAsync(notificationToAllUsersThatHaveAdInWishlist.Id, usersIds.ToList());

            return RedirectToAction("All");
        }

        public async Task<IActionResult> UnArchive(string adId)
        {
            var ad = await advertisementService.GetByIdAsync(adId);

            if (ad == null)
            {
                return RedirectToAction("All");
            }

            await advertisementService.UnarchiveByIdAsync(ad.Id);

            var notificationText = $"Your ad has been unarchived by admin - '{ad.Name}'";
            var actionLink = $"/User/Profile?id={ad.Id}";

Shoplify/Shoplify.Web/Controllers/CommentController.cs
using System.Linq;
using Microsoft.Data.SqlClient;
using Shoplify.Services.Models;

namespace Shoplify.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Domain;
    using Shoplify.Services.Interfaces;
    using Shoplify.Services.Models.Comment;
    using Shoplify.Web.BindingModels.Comment;

    [AutoValidateAntiforgeryToken]
    [Authorize]
    public class CommentController : Controller
    {
        private readonly ICommentService commentService;
        private readonly INotificationService notificationService;
        private readonly IAdvertisementService advertisementService;
        private readonly IUserAdWishlistService userAdWishlistService;
        private readonly UserManager<User> userManager;

        public CommentController(ICommentService commentService, UserManager<User> userManager, INotificationService notificationService, IAdvertisementService advertisementService, IUserAdWishlistService userAdWishlistService)
        {
            this.commentService = commentService;
            this.userManager = userManager;
            this.notificationService = notificationService;
            this.advertisementService = advertisementService;
            this.userAdWishlistService = userAdWishlistService;
        }

        public async Task<IActionResult> GetAllByAd(string id)
        {
            var comments = await commentService.GetAllByAdIdAsync(id);

            return Json(comments);
        }

        [HttpPost]
        public async Task<IActionResult> Post(CreateBindingModel input)
        {
            if (!ModelState.IsValid)
            {
                return Redirect($"/Advertisement/Details?id={input.AdvertisementId}");
            }

            var serviceModel = new CreateServiceModel
            {
                Text = input.Text,
                AdvertisementId = input.AdvertisementId,
                WrittenOn = DateTime.UtcNow,
                UserId = userManager.GetUserAsync(HttpContext.User).GetAwaiter().GetResult().Id
            };

            var comment = await commentService.PostAsync(serviceModel);
            var ad = await advertisementService.GetByIdAsync(input.AdvertisementId);

            await NotifyAsync(comment, ad);

            return Redirect($"/Advertisement/Details?id={input.AdvertisementId}");
        }

        private async Task NotifyAsync(ViewServiceModel comment, AdvertisementViewServiceModel ad)
        {
            var commentOwner = await userManager.FindByIdAsync(comment.UserId);
            var commentUserName = commentOwner.UserName;

            var adOwner = await userManager.FindByIdAsync(ad.UserId);

            var notificationActionLink = $"/Advertisement/Details?id={ad.Id}";

            if (adOwner.Id != commentOwner.Id)
            {
                var notificationText = $"{commentUserName} commented on your Ad: '{comment.Text}'";

                var notification = await notificationService.CreateNotificationAsync(notificationText, notificationActionLink);

                await notificationService.AssignNotificationToUserAsync(notification.Id, adOwner.Id);
            }

            var userIds = await userAdWishlistService.GetAllUserIdsThatHaveAdInWishlistAsync(ad.Id);

            var usersToGetNotification = userIds.Where(u => u != comment.UserId).ToList();

            if (usersToGetNotification.Count != 0)
            {
                var notificationText = $"{commentUserName} commented on an Ad in your Wishlist: '{comment.Text}'";

                var notification = await notificationService.CreateNotificationAsync(notificationText, notificationActionLink);

                await notificationService.AssignNotificationToUsersAsync(notification.Id, usersToGetNotification);
            }
        }
    }
}

Shoplify/Shoplify.Web/Controllers/ReportController.cs
using Microsoft.AspNetCore.Identity;
using Shoplify.Domain;

namespace Shoplify.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Services.Interfaces;
    using Shoplify.Services.Models.Report;
    using Shoplify.Web.BindingModels.Report;

    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class ReportController : Controller
    {
        private readonly IAdvertisementService advertisementService;
        private readonly IReportService reportService;
        private readonly INotificationService notificationService;
        private readonly UserManager<User> userManager;
        private readonly IUserService userService;

        public ReportController(IAdvertisementService advertisementService, IReportService reportService, INotificationService notificationService, UserManager<User> userManager, IUserService userService)
        {
            this.advertisementService = advertisementService;
            this.reportService = reportService;
            this.notificationService = notificationService;
            this.userManager = userManager;
            this.userService = userService;
        }

        public async Task<IActionResult> Create(string adId)
        {
            var ad = await advertisementService.GetByIdAsync(adId);

            var model = new CreateBindingModel
            {
                ReportedUserId = ad.UserId,
                ReportedAdvertisementId = ad.Id,
                ReportingUserId = User.FindFirstValue(ClaimTypes.NameIdentifier)
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateBindingModel input)
        {
            if (!ModelState.IsValid)
            {
                return Redirect($"/Report/Create?adId={input.ReportedAdvertisementId}");
            }

            var serviceModel = new ReportCreateServiceModel
            {
                Description = input.Description,
                ReportedAdvertisementId = input.ReportedAdvertisementId,
                ReportedUserId = input.ReportedUserId,
                ReportingUserId = input.ReportingUserId
            };

            await reportService.CreateAsync(serviceModel);

            var reportingUser = await userManager.FindByIdAsync(input.ReportingUserId);
            var reportedAd = await advertisementService.GetByIdAsync(input.ReportedAdvertisementId);

            var notificationText = $"{reportingUser.UserName} reported one of your ads - {reportedAd.Name}. '{input.Description}'";
            var actionLink = $"Advertisement/Details?id={reportedAd.Id}";

            var notification = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUserAsync(notification.Id, input.ReportedUserId);

            notificationText = $"{reportingUser.UserName} reported an ad - {reportedAd.Name} because of '{input.Description}'";
            actionLink = $"/Administration/Report/All";

            var notificationToAdmin = await notificationService.CreateNotificationAsync(notificationText, actionLink);
            await notificationService.AssignNotificationToUserAsync(notificationToAdmin.Id, await userService.GetAdminIdAsync());

            return Redirect($"/Advertisement/Details?id={input.ReportedAdvertisementId}");
        }
    }
}

Shoplify/Shoplify.Web/Views/Advertisement/Details.cshtml
@using System.Security.Claims
@model Shoplify.Web.ViewModels.Advertisement.DetailsViewModel
@{
    ViewData["Title"] = "Single Ad Page";
}

<section class="banner-area organic-breadcrumb">
    <div class="container">
        <div class="breadcrumb-banner d-flex flex-wrap align-items-center">
            <div class="col-first">
                <h1>Single Ad Page</h1>
            </div>
        </div>
    </div>
</section>

<div class="container">
    <div class="product-quick-view">
        <div class="row align-items-center">
            <div class="col-lg-6">

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        @for (var i = 0; i < Model.Images.Count; i++)
                        {
                            if (i == 0)
                            {
                                <div class="carousel-item active">
                                    <img class="d-block w-100" src="@Model.Images[i]" alt="image">
                                </div>
                            }
                            else
                            {
                                <div class="carousel-item">
                                    <img class="d-block w-100" src="@Model.Images[i]" alt="image">
                                </div>
                            }
                        }
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="quick-view-content element-with-date">

                    <div class="top">
                        <h3 class="head">@Model.Name</h3>
                        <div class="price d-flex align-items-center"><span class="lnr lnr-tag"></span> <span class="ml-10">$@Model.Price</span></div>

                        <div class="category">Category: <a href="/Advertisement/GetByCategory?categoryId=@Model.CategoryId&page=1">@Model.CategoryName</a></div>
                        <div class="available">SubCategory: <a href="/Advertisement/GetByCategory?categoryId=@Model.SubCategoryId&page=1">@Model.SubCategoryName</a></div>
                        <div class="available">Condition: <span>@Model.Condition</span></div>
                    </div>
                    <div class="middle">
                        <p><i class="fas fa-map-marker-alt"></i> @Model.TownName</p>
                        <p>@Model.Address</p>
                        <input style="display: none" type="text" class="utc-date" value="@Model.CreatedOn" />
                        <p class="local-date"><i class="fas fa-clock"></i> @Model.CreatedOn</p>
                    </div>

                    @if (Model.UserId != ViewData["loggedUserId"].ToString())
                    {
                        <div>
                            <div class="d-flex mt-20">
                                <a asp-controller="Conversation" asp-action="Create" asp-route-buyerId="@User.FindFirstValue(ClaimTypes.NameIdentifier)" asp-route-sellerId="@Model.UserId" asp-route-adId="@Model.Id" class="view-btn color-2"><span>Message Seller</span></a>

                                @if (Model.IsAdInLoggedUserWishlist)
                                {
                                    <a asp-controller="User" asp-action="RemoveFromWishlist" asp-route-adId="@Model.Id" class="like-btn"><i class="fas fa-heart" style="color: red"></i></a>
                                }
                                else
                                {
                                    <a asp-controller="User" asp-action="AddToWishlist" asp-route-adId="@Model.Id" class="like-btn"><i class="far fa-heart" style="color: red"></i></a>
                                }

                            </div>

                            <div class="d-flex mt-20">
                                <a asp-controller="Report" asp-action="Create" asp-route-adId="@Model.Id" class="view-btn color-2"><span>Report Ad</span></a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div>
                            <div class="d-flex mt-20">
                                <a asp-controller="Advertisement" asp-action="Edit" asp-route-id="@Model.Id" class="view-btn color-2"><span>Edit</span></a>
                            </div>
                        </div>

                        <div>
                            <div class="d-flex mt-20">
                                <a asp-controller="Advertisement" asp-action="Archive" asp-route-id="@Model.Id" class="view-btn color-2"><span>Archive</span></a>
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mb-100">
    <div class="details-tab-navigation d-flex justify-content-center mt-30">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li>
                <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-expanded="true">Description</a>
            </li>
            <li>
                <a class="nav-link" id="seller-info-tab" data-toggle="tab" href="#sellerInfo" role="tab" aria-controls="sellerInfo" aria-expanded="true">Seller Info</a>
            </li>
            <li>
                <input id="adId" type="text" value="@Model.Id" style="display: none"/>
                <a class="nav-link" id="comments-tab" data-toggle="tab" href="#comments" role="tab" aria-controls="comments" onclick="fetchComments(comments, adId)">Comments</a>
            </li>
        </ul>
    </div>
    <div class="tab-content show active" id="myTabContent">
        <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description">
            <div class="description">
                <p>@Model.Description</p>
            </div>
        </div>

        <div class="tab-pane fade" id="sellerInfo" role="tabpanel" aria-labelledby="sellerInfo">
            <div class="description">
                <h3 class="text-center margin-bottom-2rem"><a href="/User/Profile?id=@Model.UserId&orderBy=dateDesc&page=1"><i class="fas fa-user"></i> @Model.Username</a></h3>
                <h3 class="text-center"><i class="fas fa-phone-alt"></i> @Model.Phone</h3>
            </div>
        </div>

        <div class="tab-pane fade" id="comments" role="tabpanel" aria-labelledby="comments">
            <div class="review-wrapper">
                <div class="row">
                    <div class="col-xl-6">
                        <div class="total-comment">
                        </div>
                    </div>
                    <div class="col-xl-6">
                        <div class="add-review">
                            <form asp-controller="Comment" asp-action="Post" method="post">
                                <h3>Post a comment</h3>
                                <input type="text" name="AdvertisementId" value="@Model.Id" style="display: none" />
                                <textarea placeholder="Message" id="commentText" name="Text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Message'" required class="common-textarea"></textarea>
                                <button class="view-btn color-2 mt-2" type="submit"><span>Comment Now</span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/js/comments.js" asp-append-version="true"></script>
}

Shoplify/Shoplify.Web/Views/Advertisement/Promote.cshtml
@model Shoplify.Web.ViewModels.Advertisement.PromoteViewModel
@{
    ViewData["Title"] = "Promote Ad";
}
<div class="container-fluid margin-top-8rem">

    <div class="row">
        <div class="col-md-6 mx-auto mb-100">
            <div class="login-form margin-top-2rem">
                <h3 class="billing-title text-center">Promote Advertisement</h3>
                <p class="text-center mt-80 mb-40">It will be among the first displayed ads </p>
                <form method="post" asp-controller="Advertisement" asp-action="Promote">
                    <div class="form-group">
                        <input name="Id" class="form-control common-input mt-20" style="display: none" value="@Model.Id" />
                    </div>

                    <div class="form-group row mt-20 align-items-center margin-bottom-4rem">
                        <div class="form-select col-md-12">
                            <select name="PromotedDays" class="border">
                                <option value="0" disabled selected>Select Promotion Days</option>
                                <option value="1">One day - 2$</option>
                                <option value="7">One week - 6$</option>
                                <option value="14">Two weeks - 10$</option>
                                <option value="30">One Month - 20$</option>
                            </select>
                        </div>
                    </div>

                    <div id="card-element">
                        
                    </div>

                    <div id="card-errors" role="alert"></div>

                    <div class="form-group col-md-4 mx-auto">
                        <button type="submit" class="btn view-btn btn-pink color-2 mt-20 w-100"><span>Promote</span></button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="https://js.stripe.com/v3/"></script>
    <script src="~/js/client.js"></script>
}