Shoplify/Shoplify.Web/Areas/Administration/Controllers/HomeController.cs
namespace Shoplify.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Common;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

Shoplify/Shoplify.Web/Controllers/HomeController.cs
namespace Shoplify.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Threading.Tasks;

    using Microsoft.ApplicationInsights;
    using Microsoft.AspNetCore.Mvc;
    using Models;
    using Shoplify.Services.Interfaces;

    public class HomeController : Controller
    {
        private readonly IAdvertisementService advertisementService;

        public HomeController(IAdvertisementService advertisementService, TelemetryClient telemetryClient)
        {
            this.advertisementService = advertisementService;
        }

        public async Task<IActionResult> Index()
        {
            var date = DateTime.UtcNow;

            await advertisementService.ArchiveAllExpiredAdsAsync(date);
            await advertisementService.UnPromoteAllExpiredAdsAsync(date);

            return View();
        }

        public IActionResult PageNotFound()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Shoplify/Shoplify.Web/ViewComponents/AllCategoriesAndSubCategoriesListingViewComponent.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Shoplify.Web.ViewModels.Category;
using Shoplify.Web.ViewModels.CategoryAndSubCategory;
using Shoplify.Web.ViewModels.SubCategory;

namespace Shoplify.Web.ViewComponents
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Services.Interfaces;

    [ViewComponent(Name = "AllCategoriesAndSubCategoriesListing")]
    public class AllCategoriesAndSubCategoriesListingViewComponent : ViewComponent
    {
        private readonly ICategoryService categoryService;
        private readonly ISubCategoryService subCategoryService;

        public AllCategoriesAndSubCategoriesListingViewComponent(ICategoryService categoryService, ISubCategoryService subCategoryService)
        {
            this.categoryService = categoryService;
            this.subCategoryService = subCategoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var viewModel = new ListingViewModel
            {
                CategoriesWithSubCategories = new Dictionary<CategoryViewModel, List<SubCategoryViewModel>>()
            };

            var categories = categoryService.GetAll();

            foreach (var category in categories)
            {
                var subCategories = await subCategoryService
                    .GetAllByCategoryId(category.Id)
                    .OrderBy(s => s.Name)
                    .Select(s => new SubCategoryViewModel
                    {
                        Name = s.Name,
                        Id = s.Id
                    })
                    .ToListAsync();

                viewModel.CategoriesWithSubCategories
                    .Add(new CategoryViewModel { Name = category.Name, Id = category.Id, CssIconClass = category.CssIconClass }, subCategories);
            }

            return View(viewModel);
        }
    }
}

Shoplify/Shoplify.Web/ViewComponents/LastAddedAdsViewComponent.cs
namespace Shoplify.Web.ViewComponents
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Common;
    using Shoplify.Domain;
    using Shoplify.Services.Interfaces;

    public class LastAddedAdsViewComponent : ViewComponent
    {
        private readonly IAdvertisementService advertisementService;
        private readonly ICategoryService categoryService;
        private readonly ISubCategoryService subCategoryService;
        private readonly ITownService townService;
        private readonly UserManager<User> userManager;

        public LastAddedAdsViewComponent(IAdvertisementService advertisementService, UserManager<User> userManager, ICategoryService categoryService, ISubCategoryService subCategoryService, ITownService townService)
        {
            this.advertisementService = advertisementService;
            this.userManager = userManager;
            this.categoryService = categoryService;
            this.subCategoryService = subCategoryService;
            this.townService = townService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = userManager.GetUserId(HttpContext.User);

            var ads = await advertisementService.GetLatestAsync(8, userId);

            var result = new List<ViewModels.Advertisement.ListingViewModel>();

            foreach (var ad in ads)
            {
                var category = await categoryService.GetByIdAsync(ad.CategoryId);

                string subCategoryName = null;

                if (await subCategoryService.ContainsByIdAsync(ad.SubCategoryId))
                {
                    var subCategory = await subCategoryService.GetByIdAsync(ad.SubCategoryId);
                    subCategoryName = subCategory.Name;
                }

                var town = await townService.GetByIdAsync(ad.TownId);

                var adViewModel = new ViewModels.Advertisement.ListingViewModel
                {
                    Address = ad.Address,
                    CategoryName = category.Name,
                    CreatedOn = ad.CreatedOn.ToString(GlobalConstants.DateTimeFormat),
                    Id = ad.Id,
                    Name = ad.Name,
                    Price = ad.Price,
                    SubCategoryName = subCategoryName,
                    TownName = town.Name,
                    Image = ad.Images.FirstOrDefault()
                };

                result.Add(adViewModel);
            }

            return View(result);
        }
    }
}

Shoplify/Shoplify.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="container-fluid margin-top-4rem home-page-container">

    @if (User.Identity.Name != null)
    {
        <partial name="_SearchbarPartial" />
        @await Component.InvokeAsync("AllCategoriesAndSubCategoriesListing")
        @await Component.InvokeAsync("LastAddedAds")
    }
    else
    {
        <section class="banner-area relative mb-100 margin-top-4rem" id="home">
            <div class="container-fluid">
                <div class="row fullscreen align-items-center justify-content-center">
                    <div class="col-lg-6 col-md-12 d-flex align-self-end img-right no-padding">
                        <img class="img-fluid" src="~/img/cta.png" alt="">
                    </div>
                    <div class="banner-content col-lg-6 col-md-12">
                        <h1 class="title-top text-uppercase">Welcome!</h1>
                        <h1 class="text">
                            Find Anything <br>
                            that you need
                        </h1>
                        <h1>
                            Or Sell Anything
                        </h1>
                        <button class="primary-btn text-uppercase"><a href="/Identity/Account/Register">Register Now</a></button>
                    </div>
                </div>
            </div>
        </section>
    }

</div>

Shoplify/Shoplify.Web/Views/Home/PageNotFound.cshtml
@{
    ViewBag.Title = "404 Not Found";
}

<div class="container-fluid padding-top-8rem padding-bottom-8rem">
    <div class="row text-center">
        <div class="col-lg-6 offset-lg-3 col-sm-6 offset-sm-3 col-12 p-3 error-main">
            <div class="row py-5">
                <div class="col-lg-8 col-12 col-sm-10 offset-lg-2 offset-sm-1">
                    <h1>404</h1>
                    <h2>Page not found</h2>
                </div>
            </div>
        </div>
    </div>
</div>