Shoplify/Shoplify.Web/Areas/Administration/ViewModels/User/UserListingPageViewModel.cs
namespace Shoplify.Web.Areas.Administration.ViewModels.User
{
    using System.Collections.Generic;

    public class UserListingPageViewModel
    {
        public ICollection<UserViewModel> Users { get; set; } = new List<UserViewModel>();

        public string OrderParam { get; set; }

        public int TotalUsersCount { get; set; }

        public int CurrentPage { get; set; }

        public int LastPage { get; set; }
    }
}

Shoplify/Shoplify.Web/Areas/Administration/ViewModels/User/UserViewModel.cs
namespace Shoplify.Web.Areas.Administration.ViewModels.User
{
    public class UserViewModel
    {
        public string Id { get; set; }

        public string Username { get; set; }

        public string RegisteredOn { get; set; }

        public string BannedOn { get; set; }

        public bool IsBanned { get; set; }
    }
}

Shoplify/Shoplify.Web/Areas/Administration/Controllers/UserController.cs
namespace Shoplify.Web.Areas.Administration.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Common;
    using Shoplify.Services.Interfaces;
    using Shoplify.Web.Areas.Administration.ViewModels.User;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> All(int page = 1, string orderBy = "nameAsc")
        {
            if (page <= 0)
            {
                return Redirect("/Panel/Index");
            }

            var usersCount = await userService.GetAllUserCountWithoutAdminAsync();
            var lastPage = usersCount / GlobalConstants.UsersOnPageCount + 1;

            if (usersCount % GlobalConstants.UsersOnPageCount == 0 && usersCount > 0)
            {
                lastPage -= 1;
            }

            if (page > lastPage)
            {
                return Redirect("/Panel/Index");
            }

            var users = await userService.GetAllUsersWithoutAdminAsync(page, GlobalConstants.UsersOnPageCount, orderBy);

            var viewModel = new UserListingPageViewModel
            {
                TotalUsersCount = usersCount,
                CurrentPage = page,
                LastPage = lastPage,
                OrderParam = $"orderBy={orderBy}",
                Users = new List<UserViewModel>()
            };

            foreach (var user in users)
            {
                viewModel.Users.Add(new UserViewModel
                {
                    BannedOn = user.BannedOn.ToString(GlobalConstants.DateTimeFormat),
                    Id = user.Id,
                    IsBanned = user.IsBanned,
                    RegisteredOn = user.RegisteredOn.ToString(GlobalConstants.DateTimeFormat),
                    Username = user.Username
                });
            }

            return View(viewModel);
        }
        public async Task<IActionResult> RegisteredThisWeek()
        {
            var userCountsByDays = await userService.GetNewUsersCountByDaysFromThisWeekAsync();

            return Json(userCountsByDays);
        }

        public async Task<IActionResult> Unban(string userId)
        {
            await userService.UnbanUserByIdAsync(userId);

            return RedirectToAction("All");
        }

        public async Task<IActionResult> Ban(string userId)
        {
           await userService.BanUserByIdAsync(userId);

           return RedirectToAction("All");
        }
    }
}

Shoplify/Shoplify.Web/Controllers/AdvertisementController.cs
namespace Shoplify.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Configuration;
    using Shoplify.Common;
    using Shoplify.Domain;
    using Shoplify.Services.Interfaces;
    using Shoplify.Services.Models;
    using Shoplify.Services.Models.Advertisement;
    using Shoplify.Web.BindingModels.Advertisement;
    using Shoplify.Web.ViewModels.Advertisement;
    using Shoplify.Web.ViewModels.Category;
    using Shoplify.Web.ViewModels.SubCategory;
    using Stripe;

    [AutoValidateAntiforgeryToken]
    public class AdvertisementController : Controller
    {
        private IAdvertisementService advertisementService;
        private ICategoryService categoryService;
        private ISubCategoryService subCategoryService;
        private ITownService townService;
        private IUserAdWishlistService userAdWishlistService;
        private readonly UserManager<User> userManager;
        private readonly IConfiguration configuration;
        private readonly INotificationService notificationService;
        private readonly IUserService userService;

        public AdvertisementController(IAdvertisementService advertisementService, ICategoryService categoryService, ISubCategoryService subCategoryService, ITownService townService, IUserAdWishlistService userAdWishlistService, UserManager<User> userManager, IConfiguration configuration, INotificationService notificationService, IUserService userService)
        {
            this.advertisementService = advertisementService;
            this.categoryService = categoryService;
            this.subCategoryService = subCategoryService;
            this.townService = townService;
            this.userManager = userManager;
            this.userAdWishlistService = userAdWishlistService;
            this.configuration = configuration;
            this.notificationService = notificationService;
            this.userService = userService;
        }

        [Authorize]
        public IActionResult Create()
        {
            return View(new CreateBindingModel());
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateBindingModel advertisement)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("/Advertisement/Create");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var advertisementServiceModel = new AdvertisementCreateServiceModel
            {
                Name = advertisement.Name,
                Price = advertisement.Price,
                Description = advertisement.Description,
                Condition = advertisement.Condition,
                CategoryId = advertisement.CategoryId,
                SubCategoryId = advertisement.SubCategoryId,
                TownId = advertisement.TownId,
                Address = advertisement.Address,
                Number = advertisement.Number,
                UserId = userId,
                Images = advertisement.Images,
            };

            await advertisementService.CreateAsync(advertisementServiceModel);

            await NotifyOnAdCreateAsync(advertisementServiceModel);

            return Redirect("/Home/Index");
        }

        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var ad = await advertisementService.GetByIdAsync(id);

            if (ad.UserId != userId)
            {
                return Redirect($"/Advertisement/Details?id={id}");
            }

            var modelForView = new EditBindingModel()
            {
                Id = ad.Id,
                Name = ad.Name,
                Address = ad.Address,
                CategoryId = ad.CategoryId,
                Condition = ad.Condition,
                Description = ad.Description,
                Number = ad.Number,
                Price = ad.Price,
                SubCategoryId = ad.SubCategoryId,
                TownId = ad.TownId,
                UserId = ad.UserId
            };

            return View(modelForView);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(EditBindingModel advertisement)
        {
            if (!ModelState.IsValid)
            {
                return Redirect($"/Advertisement/Edit?id={advertisement.Id}");
            }

            var advertisementServiceModel = new AdvertisementEditServiceModel()
            {
                Id = advertisement.Id,
                Name = advertisement.Name,
                Price = advertisement.Price,
                Description = advertisement.Description,
                Condition = advertisement.Condition,
                CategoryId = advertisement.CategoryId,
                SubCategoryId = advertisement.SubCategoryId,
                TownId = advertisement.TownId,
                Address = advertisement.Address,
                Number = advertisement.Number,
                UserId = advertisement.UserId,
                Images = advertisement.Images
            };

            await advertisementService.EditAsync(advertisementServiceModel);

            await NotifyOnAdEditAsync(advertisement.Id);

            return Redirect($"/Advertisement/Details?id={advertisement.Id}");
        }

        [Authorize]
        public async Task<IActionResult> GetByCategory(string categoryId, string orderBy = "dateDesc", int page = 1)
        {
            if (page <= 0)
            {
                return Redirect("/Home/Index");
            }

            var adsCount = await advertisementService.GetCountByCategoryIdAsync(categoryId);
            var lastPage = adsCount / GlobalConstants.AdsOnPageCount + 1;

            if (adsCount % GlobalConstants.AdsOnPageCount == 0 && adsCount > 0)
            {
                lastPage -= 1;
            }

            if (page > lastPage)
            {
                return Redirect("/Home/Index");
            }

            var ads = await advertisementService.GetByCategoryIdAsync(categoryId, page, GlobalConstants.AdsOnPageCount, orderBy);

            ads = OrderAds(ads, orderBy);

            var result = new ListingPageViewModel();

            result = await GetCategoriesAndSubCategoriesAsync(result);

            foreach (var ad in ads)
            {
                var category = await categoryService.GetByIdAsync(ad.CategoryId);

                string subCategoryName = null;

                if (await subCategoryService.ContainsByIdAsync(ad.SubCategoryId))
                {
                    var subCategory = await subCategoryService.GetByIdAsync(ad.SubCategoryId);
                    subCategoryName = subCategory.Name;
                }

                var town = await townService.GetByIdAsync(ad.TownId);

                var adViewModel = new ListingViewModel
                {
                    Address = ad.Address,
                    CategoryName = category.Name,
                    CreatedOn = ad.CreatedOn.ToString(GlobalConstants.DateTimeFormat),
                    Id = ad.Id,
                    Name = ad.Name,
                    Price = ad.Price,
                    SubCategoryName = subCategoryName,
                    TownName = town.Name,
                    Image = ad.Images.FirstOrDefault(),
                    IsPromoted = ad.IsPromoted,
                };

                result.Advertisements.Add(adViewModel);
            }

            result.CurrentPage = page;
            result.LastPage = lastPage;
            result.TotalAdsCount = adsCount;
            result.GetByParam = "GetByCategory";
            result.OrderParam = "orderBy=" + orderBy;
            result.PageParam = "categoryId=" + categoryId;

            return View("Listing", result);
        }

        [Authorize]
        public async Task<IActionResult> GetBySearch(string search, string orderBy = "dateDesc", int page = 1)
        {
            if (page <= 0)
            {
                return Redirect("/Home/Index");
            }

            var adsCount = await advertisementService.GetCountBySearchAsync(search);
            var lastPage = adsCount / GlobalConstants.AdsOnPageCount + 1;

            if (adsCount % GlobalConstants.AdsOnPageCount == 0 && adsCount > 0)
            {
                lastPage -= 1;
            }

            if (page > lastPage)
            {
                return Redirect("/Home/Index");
            }

            var ads = await advertisementService.GetBySearchAsync(search, page, GlobalConstants.AdsOnPageCount, orderBy);
            ads = OrderAds(ads, orderBy);

            var result = new ListingPageViewModel();

            result = await GetCategoriesAndSubCategoriesAsync(result);

            foreach (var ad in ads)
            {
                var category = await categoryService.GetByIdAsync(ad.CategoryId);

                string subCategoryName = null;

                if (await subCategoryService.ContainsByIdAsync(ad.SubCategoryId))
                {
                    var subCategory = await subCategoryService.GetByIdAsync(ad.SubCategoryId);
                    subCategoryName = subCategory.Name;
                }

                var town = await townService.GetByIdAsync(ad.TownId);

                var adViewModel = new ListingViewModel
                {
                    Address = ad.Address,
                    CategoryName = category.Name,
                    CreatedOn = ad.CreatedOn.ToString(GlobalConstants.DateTimeFormat),
                    Id = ad.Id,
                    Name = ad.Name,
                    Price = ad.Price,

Shoplify/Shoplify.Web/Controllers/ConversationController.cs
namespace Shoplify.Web.Controllers
{
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Common;
    using Shoplify.Domain;
    using Shoplify.Services.Interfaces;
    using Shoplify.Web.ViewModels.Conversation;

    public class ConversationController : Controller
    {
        private IConversationService conversationService;
        private IAdvertisementService advertisementService;
        private UserManager<User> userManager;

        public ConversationController(IConversationService conversationService, IAdvertisementService advertisementService, UserManager<User> userManager)
        {
            this.conversationService = conversationService;
            this.advertisementService = advertisementService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Create(string buyerId, string sellerId, string adId)
        {
            if (await conversationService.ConversationExistsAsync(buyerId, sellerId, adId))
            {
                var id = await conversationService.GetIdAsync(buyerId, sellerId, adId);

                return Redirect($"/Message/Chat?conversationId={id}");
            }

            var conversation = await conversationService.CreateConversationAsync(buyerId, sellerId, adId);

            return Redirect($"/Message/Chat?conversationId={conversation.Id}");
        }

        public async Task<IActionResult> GetAllCount(string userId)
        {
            var conversationsCount = await conversationService.GetAllUnReadByUserIdCountAsync(userId);

            return Json(conversationsCount);
        }

        public async Task<IActionResult> All()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var conversations = await conversationService.GetAllByUserIdAsync(userId);

            var viewModel = new List<ConversationViewModel>();

            foreach (var conversation in conversations)
            {
                var ad = await advertisementService.GetByIdAsync(conversation.AdvertisementId);

                var buyer = await userManager.FindByIdAsync(conversation.BuyerId);
                var seller = await userManager.FindByIdAsync(conversation.SellerId);

                var conversationViewModel = new ConversationViewModel
                {
                    Id = conversation.Id,
                    BuyerId = conversation.BuyerId,
                    SellerId = conversation.SellerId,
                    BuyerName = buyer.UserName,
                    SellerName = seller.UserName,
                    AdvertisementId = ad.Id,
                    AdvertisementName = ad.Name,
                    StartedOn = conversation.StartedOn.ToString(GlobalConstants.DateTimeFormat)
                };

                if (ad.UserId == userId && userId == conversation.SellerId)
                {
                    conversationViewModel.IsRead = conversation.IsReadBySeller;
                }else
                {
                    conversationViewModel.IsRead = conversation.IsReadByBuyer;
                }

                viewModel.Add(conversationViewModel);
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Archive(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            await conversationService.ArchiveAsync(id, userId);

            return Redirect("All");
        }

        public async Task<IActionResult> ArchiveAll()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            await conversationService.ArchiveAllAsync(userId);

            return Redirect("All");
        }
    }
}

Shoplify/Shoplify.Web/Views/User/ArchivedAds.cshtml
@using Shoplify.Common
@model Shoplify.Web.ViewModels.User.ArchivedAdsViewModel
@{
    ViewData["Title"] = "Archived Ads";
}
<div class="container-fluid margin-top-4rem">
    <div class="row">
        <div class="col-md-8 mx-auto mb-100">
            @if (Model.TotalAdsCount == 0)
            {
                <h1 class="text-center margin-bottom-4rem margin-top-4rem">You have no archived ads...</h1>
            }
            else
            {
                <h2 class="text-center margin-top-4rem margin-bottom-2rem">My Archived Ads</h2>
                <table class="table table-zebra">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Category</th>
                            <th scope="col">Created On</th>
                            <th scope="col">Archived On</th>
                            <th scope="col">Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Advertisements.Count == 0)
                        {
                            <h1 class="text-center margin-bottom-4rem margin-top-4rem">No archived ads...</h1>
                        }
                        @for (var i = 0; i < Model.Advertisements.Count; i++)
                        {
                            <tr>
                                <th scope="row">@Model.Advertisements[i].Name</th>
                                <td>@Model.Advertisements[i].Price</td>
                                <td>@Model.Advertisements[i].Category</td>

                                <td class="element-with-date">
                                    <input style="display: none" type="text" class="utc-date" value="@Model.Advertisements[i].CreatedOn" />
                                    <p class="local-date">@Model.Advertisements[i].CreatedOn</p>
                                </td>
                                
                                <td class="element-with-date">
                                    <input style="display: none" type="text" class="utc-date" value="@Model.Advertisements[i].ArchivedOn" />
                                    <p class="local-date">@Model.Advertisements[i].ArchivedOn</p>
                                </td>

                                <td>
                                    <div class="button-holder">
                                        <a asp-controller="Advertisement" asp-action="Details" asp-route-id="@Model.Advertisements[i].Id" asp-route-returnUrl="@Url.Action("Profile", "User", new {})" class="btn btn-details">Details</a>
                                    </div>
                                </td>
                            </tr>
                        }

                    </tbody>

                </table>
                <div class="filter-bar d-flex flex-wrap align-items-center">
                    <div class="pagination mx-auto">
                        @{
                            var prevPage = Model.CurrentPage - 1;
                            var nextPage = Model.CurrentPage + 1;
                        }
                        @if (Model.CurrentPage != 1)
                        {
                            <a asp-controller="User" asp-action="ArchivedAds" asp-route-page="@prevPage" class="prev-arrow "><i class="fas fa-arrow-left"></i></a>
                        }

                        @for (var j = 1; j <= (Model.TotalAdsCount / GlobalConstants.AdsOnPageCount) + 1; j++)
                        {
                            @if (j == Model.CurrentPage)
                            {
                                <a class="active" asp-controller="User" asp-action="ArchivedAds" asp-route-page="@j">@j</a>
                            }
                            else if (j >= Model.CurrentPage - 4 && (j <= Model.CurrentPage + 4 && j <= Model.LastPage))
                            {
                                <a asp-controller="User" asp-action="ArchivedAds" asp-route-page="@j">@j</a>
                            }
                        }

                        @if (Model.CurrentPage != Model.LastPage)
                        {
                            <a asp-controller="User" asp-action="ArchivedAds" asp-route-page="@nextPage" class="next-arrow"><i class="fas fa-arrow-right"></i></a>
                        }

                    </div>
                </div>
            }
        </div>
    </div>
</div>

Shoplify/Shoplify.Web/Views/User/BannedAds.cshtml
@using Shoplify.Common
@model Shoplify.Web.ViewModels.User.BannedAdsViewModel
@{
    ViewData["Title"] = "Banned Ads";
}
<div class="container-fluid margin-top-4rem">
    <div class="row">
        <div class="col-md-8 mx-auto mb-100">
            @if (Model.TotalAdsCount == 0)
            {
                <h1 class="text-center margin-bottom-4rem margin-top-4rem">You have no banned ads...</h1>
            }
            else
            {
                <h2 class="text-center margin-top-4rem margin-bottom-2rem">My Banned Ads</h2>
                <table class="table table-zebra">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Category</th>
                            <th scope="col">Created On</th>
                            <th scope="col">Banned On</th>
                            <th scope="col">Details</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if (Model.Advertisements.Count == 0)
                    {
                        <h1 class="text-center margin-bottom-4rem margin-top-4rem">No banned ads...</h1>
                    }
                        @for (var i = 0; i < Model.Advertisements.Count; i++)
                        {
                    <tr>
                        <th scope="row">@Model.Advertisements[i].Name</th>
                        <td>@Model.Advertisements[i].Price</td>
                        <td>@Model.Advertisements[i].Category</td>

                        <td class="element-with-date">
                            <input style="display: none" type="text" class="utc-date" value="@Model.Advertisements[i].CreatedOn" />
                            <p class="local-date">@Model.Advertisements[i].CreatedOn</p>
                        </td>
                        
                        <td class="element-with-date">
                            <input style="display: none" type="text" class="utc-date" value="@Model.Advertisements[i].BannedOn" />
                            <p class="local-date">@Model.Advertisements[i].BannedOn</p>
                        </td>

                        <td>
                            <div class="button-holder">
                                <a asp-controller="Advertisement" asp-action="Details" asp-route-id="@Model.Advertisements[i].Id" asp-route-returnUrl="@Url.Action("Profile", "User", new {})" class="btn btn-details">Details</a>
                            </div>
                        </td>
                    </tr>
                        }

                    </tbody>

                </table>
                <div class="filter-bar d-flex flex-wrap align-items-center">
                    <div class="pagination mx-auto">
                        @{
                            var prevPage = Model.CurrentPage - 1;
                            var nextPage = Model.CurrentPage + 1;
                        }
                        @if (Model.CurrentPage != 1)
                        {
                            <a asp-controller="User" asp-action="BannedAds" asp-route-page="@prevPage" class="prev-arrow "><i class="fas fa-arrow-left"></i></a>
                        }

                        @for (var j = 1; j <= (Model.TotalAdsCount / GlobalConstants.AdsOnPageCount) + 1; j++)
                        {
                            @if (j == Model.CurrentPage)
                            {
                                <a class="active" asp-controller="User" asp-action="BannedAds" asp-route-page="@j">@j</a>
                            }
                            else if (j >= Model.CurrentPage - 4 && (j <= Model.CurrentPage + 4 && j <= Model.LastPage))
                            {
                                <a asp-controller="User" asp-action="BannedAds" asp-route-page="@j">@j</a>
                            }
                        }

                        @if (Model.CurrentPage != Model.LastPage)
                        {
                            <a asp-controller="User" asp-action="BannedAds" asp-route-page="@nextPage" class="next-arrow"><i class="fas fa-arrow-right"></i></a>
                        }

                    </div>
                    </div>
                    }
        </div>
    </div>
</div>

Shoplify/Shoplify.Web/Views/User/Wishlist.cshtml
@using System.Security.Claims
@using Shoplify.Common
@model Shoplify.Web.ViewModels.User.WishlistViewModel
@{
    ViewData["Title"] = "Wishlist";
}
<div class="container-fluid margin-top-4rem">
    <div class="row">
        <div class="col-md-8 mx-auto mb-100">
            <h2 class="text-center margin-top-4rem margin-bottom-2rem">Wishlist</h2>
            <table class="table table-zebra">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Category</th>
                        <th scope="col">User</th>
                        <th scope="col">Created On</th>
                        <th scope="col">Details</th>
                        <th scope="col">Message</th>
                        <th scope="col">Remove</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Advertisements.Count == 0)
                    {
                        <h1 class="text-center margin-bottom-4rem margin-top-4rem">Sorry, no ads found...</h1>
                    }

                    @for (var i = 0; i < Model.Advertisements.Count; i++)
                    {
                <tr class="element-with-date">
                    <th scope="row">@Model.Advertisements[i].Name</th>
                    <td>@Model.Advertisements[i].Price</td>
                    <td>@Model.Advertisements[i].Category</td>
                    <td>@Model.Advertisements[i].UserName</td>
                    
                    <td class="d-none">
                        <input style="display: none" type="text" class="utc-date" value="@Model.Advertisements[i].CreatedOn" />
                    </td>

                    <td class="local-date">@Model.Advertisements[i].CreatedOn</td>

                    <td>
                        <div class="button-holder">
                            <a asp-controller="Advertisement" asp-action="Details" asp-route-id="@Model.Advertisements[i].Id" asp-route-returnUrl="@Url.Action("Profile", "User", new { })" class="btn btn-details">Details</a>
                        </div>
                    </td>

                    <td>
                        <div class="button-holder">
                            <a asp-controller="Conversation" asp-action="Create" asp-route-buyerId="@User.FindFirstValue(ClaimTypes.NameIdentifier)" asp-route-sellerId="@Model.Advertisements[i].UserId" asp-route-adId="@Model.Advertisements[i].Id" asp-route-returnUrl="@Url.Action("Profile", "User", new { })" class="btn btn-primary">Message</a>
                        </div>
                    </td>

                    <td>
                        <div class="button-holder">
                            <a asp-controller="User" asp-action="RemoveFromWishlist" asp-route-adId="@Model.Advertisements[i].Id" class="btn btn-danger">Remove</a>
                        </div>
                    </td>
                </tr>
                    }

                </tbody>

            </table>
            <div class="filter-bar d-flex flex-wrap align-items-center">
                <div class="pagination mx-auto">
                    @{
                        var prevPage = Model.CurrentPage - 1;
                        var nextPage = Model.CurrentPage + 1;
                    }
                    @if (Model.CurrentPage != 1)
                    {
                        <a asp-controller="User" asp-action="Wishlist" asp-route-page="@prevPage" class="prev-arrow "><i class="fas fa-arrow-left"></i></a>
                    }

                    @for (var j = 1; j <= (Model.TotalAdsCount / GlobalConstants.AdsOnPageCount) + 1; j++)
                    {
                        @if (j == Model.CurrentPage)
                        {
                            <a class="active" asp-controller="User" asp-action="Wishlist" asp-route-page="@j">@j</a>
                        }
                        else if (j >= Model.CurrentPage - 4 && (j <= Model.CurrentPage + 4 && j <= Model.LastPage))
                        {
                            <a asp-controller="User" asp-action="Wishlist" asp-route-page="@j">@j</a>
                        }
                    }

                    @if (Model.CurrentPage != Model.LastPage)
                    {
                        <a asp-controller="User" asp-action="Wishlist" asp-route-page="@nextPage" class="next-arrow"><i class="fas fa-arrow-right"></i></a>
                    }

                </div>
            </div>
        </div>
    </div>
</div>