Shoplify/Shoplify.Web/ViewModels/Notification/NotificationViewModel.cs
namespace Shoplify.Web.ViewModels.Notification
{
    public class NotificationViewModel
    {
        public string Id { get; set; }

        public string Text { get; set; }

        public string CreatedOn { get; set; }

        public string ActionLink { get; set; }
    }
}

Shoplify/Shoplify.Web/Controllers/NotificationController.cs
using Shoplify.Common;

namespace Shoplify.Web.Controllers
{
    using System.Collections.Generic;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Shoplify.Services.Interfaces;
    using Shoplify.Web.ViewModels.Notification;

    [Authorize]
    public class NotificationController : Controller
    {
        private readonly INotificationService notificationService;

        public NotificationController(INotificationService notificationService)
        {
            this.notificationService = notificationService;
        }

        public async Task<IActionResult> GetAllCount(string userId)
        {
            var notificationsCount = await notificationService.GetAllUnReadByUserIdCountAsync(userId);

            return Json(notificationsCount);
        }

        public async Task<IActionResult> All()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var notifications = await notificationService.GetAllUnReadByUserIdAsync(userId);

            var viewModel = new List<NotificationViewModel>();

            foreach (var notification in notifications)
            {
                viewModel.Add(new NotificationViewModel
                {
                    ActionLink = notification.ActionLink,
                    Id = notification.Id,
                    Text = notification.Text,
                    CreatedOn = notification.CreatedOn.ToString(GlobalConstants.DateTimeFormat)
                });
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Mark(string userId, string nId)
        {
            await notificationService.MarkNotificationAsReadAsync(nId, userId);

            return Redirect($"/Notification/All?userId={userId}");
        }

        public async Task<IActionResult> MarkAll(string userId)
        {
            await notificationService.MarkAllNotificationsAsReadAsync(userId);

            return Redirect($"/Notification/All?userId={userId}");
        }
    }
}

Shoplify/Shoplify.Web/Views/Notification/All.cshtml
@using System.Security.Claims
@model List<Shoplify.Web.ViewModels.Notification.NotificationViewModel>
@{
    ViewData["Title"] = "Notifications";
}
<div class="container-fluid margin-top-4rem">
    <div class="row">
        <div class="col-md-8 mx-auto mb-100">
            @if (!Model.Any())
            {
                <h1 class="text-center margin-bottom-4rem margin-top-4rem">You have no new notifications.</h1>
            }
            else
            {
                <div class="text-center margin-top-4rem">
                    <a asp-controller="Notification" asp-action="MarkAll" asp-route-userId="@User.FindFirstValue(ClaimTypes.NameIdentifier)" class="btn btn-details">Mark All As Read</a>
                </div>

                <h2 class="text-center margin-top-4rem margin-bottom-2rem">My Notifications</h2>
                <table class="table">
                    <tbody>
                        @for (var i = 0; i < Model.Count(); i++)
                        {
                        <tr class="element-with-date">
                            <th scope="row" class="font-size-1-1rem">@Model[i].Text</th>
                            
                            <td class="d-none">
                                <input style="display: none" type="text" class="utc-date" value="@Model[i].CreatedOn" />
                            </td>
                            
                            <td class="font-size-1-1rem local-date">@Model[i].CreatedOn</td>

                            <td>
                                <div class="button-holder">
                                    <a href="@Model[i].ActionLink" class="btn btn-details">View</a>
                                </div>
                            </td>

                            <td>
                                <div class="button-holder">
                                    <a asp-controller="Notification" asp-action="Mark" asp-route-userId="@User.FindFirstValue(ClaimTypes.NameIdentifier)" asp-route-nId="@Model[i].Id" class="btn btn-details">Mark As Read</a>
                                </div>
                            </td>
                        </tr>
                        }

                    </tbody>

                </table>

            }
        </div>
    </div>
</div>